# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
name: Factory Reporter
description: Reports build pipeline status to Vespa Factory
author: https://github.com/vespa-engine
requirements: []
configuration:
  properties:
    pipeline-id:
      type: integer
      description: "The Vespa Factory pipeline ID to report status to"
    first-step:
      type: boolean
      description: "Is this the first step? Yes: Create a build, No: Update the build"
    job-type:
        type: string
        description: "The type of job being reported (e.g., 'build', 'release', 'test'). Defaults to 'build'."
        default: 'build'
    build-platform:
        type: string
        description: "The factory build platform, only used for build jobs. Defaults to 'opensource_centos7'."
        default: 'opensource_centos7'

  additionalProperties: false
  required:
    - pipeline-id
    - first-step

hooks:
  pre-command:
    command: "hooks/pre-command"
  post-command:
    command: "hooks/post-command"
